services:
  camarigor-tdisplay-stack_init:
    image: ghcr.io/camarigor/tdisplay-init:1.0.0
    user: "0"
    restart: "no"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${APP_DATA_DIR}:/app-data

  camarigor-tdisplay-stack:
    image: ghcr.io/camarigor/tdisplay-data-collector:1.0.0
    restart: on-failure
    stop_grace_period: 10s
    read_only: true
    tmpfs:
      - /tmp
    depends_on:
      camarigor-tdisplay-stack_init:
        condition: service_completed_successfully
    env_file:
      - ${APP_DATA_DIR}/data-collector.env
    volumes:
      - ${APP_DATA_DIR}/data:/data
    security_opt:
      - no-new-privileges:true

  camarigor-tdisplay-stack_telegraf-broker:
    image: telegraf:1.31-alpine
    restart: on-failure
    network_mode: host
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    depends_on:
      camarigor-tdisplay-stack_init:
        condition: service_completed_successfully
    env_file:
      - ${APP_DATA_DIR}/telegraf-broker.env
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/hostname:/host/etc/hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_DATA_DIR}/telegraf-broker.conf:/etc/telegraf/telegraf.conf:ro

  camarigor-tdisplay-stack_telegraf-router:
    image: telegraf:1.31-alpine
    restart: on-failure
    network_mode: host
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    depends_on:
      camarigor-tdisplay-stack_init:
        condition: service_completed_successfully
    env_file:
      - ${APP_DATA_DIR}/telegraf-router.env
    volumes:
      - ${APP_DATA_DIR}/telegraf-router.conf:/etc/telegraf/telegraf.conf:ro

  camarigor-tdisplay-stack_firmware-server:
    image: nginx:alpine
    restart: on-failure
    network_mode: host
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
    security_opt:
      - no-new-privileges:true
    depends_on:
      camarigor-tdisplay-stack_init:
        condition: service_completed_successfully
    volumes:
      - ${APP_DATA_DIR}/firmware:/usr/share/nginx/html:ro
      - ${APP_DATA_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro
